name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:

  # Auto-publish when version is increased
  publish-job:
    # Only try to publish if branch is `main`
    if: |
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
    # 1. Publish the sub-package first
    - uses: etils-actions/pypi-auto-publish@main  # /!\ <<<< Use `@1` instead of `@main`
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN_DEPS }}
        path: "./sub-project/"
        pkg-name: epot_test_deps
        # No GitHub release here

    # 2. Publish top package
    - uses: etils-actions/pypi-auto-publish@main  # /!\ <<<< Use `@1` instead of `@main`
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: true
        pkg-name: epot_test
    
